// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introducing', // Category name
      collapsed: false, // Set to true if you want it collapsed by default
      items: [
        'Introducing/AboutApp',
        'Introducing/QuickStart',
        'Introducing/SupportedDevices',
      ],
    },
    {
      type: 'category',
      label: 'Application',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'BlockBuilder',
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Blocks',
              collapsed: false,
              items: [
                'Application/BlockBuilder/Blocks/BlocksIntroducing',
                'Application/BlockBuilder/Blocks/Light',
                'Application/BlockBuilder/Blocks/Motors',
                'Application/BlockBuilder/Blocks/Sensors',
                'Application/BlockBuilder/Blocks/Events',
                'Application/BlockBuilder/Blocks/Control',
                'Application/BlockBuilder/Blocks/Operators',
                'Application/BlockBuilder/Blocks/Variables',
                'Application/BlockBuilder/Blocks/Lists',
                'Application/BlockBuilder/Blocks/MyBlocks',
                'Application/BlockBuilder/Blocks/DashboardControllers',
                'Application/BlockBuilder/Blocks/Gamepad',
              ],
            },
          ],
        },
      ],
    },
  ],
  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
